// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: net/pocrd/api/entity/Api_BookInfo.proto

package net.pocrd.api.entity;

public final class ApiBookInfo {
  private ApiBookInfo() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface Api_BookInfoOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // optional int32 crid = 1;
    boolean hasCrid();
    int getCrid();
    
    // optional int32 bookid = 2;
    boolean hasBookid();
    int getBookid();
    
    // optional string bookName = 3;
    boolean hasBookName();
    String getBookName();
    
    // optional string author = 4;
    boolean hasAuthor();
    String getAuthor();
    
    // optional int32 authorid = 5;
    boolean hasAuthorid();
    int getAuthorid();
    
    // optional string url = 6;
    boolean hasUrl();
    String getUrl();
  }
  public static final class Api_BookInfo extends
      com.google.protobuf.GeneratedMessage
      implements Api_BookInfoOrBuilder {
    // Use Api_BookInfo.newBuilder() to construct.
    private Api_BookInfo(Builder builder) {
      super(builder);
    }
    private Api_BookInfo(boolean noInit) {}
    
    private static final Api_BookInfo defaultInstance;
    public static Api_BookInfo getDefaultInstance() {
      return defaultInstance;
    }
    
    public Api_BookInfo getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return net.pocrd.api.entity.ApiBookInfo.internal_static_net_pocrd_api_entity_Api_BookInfo_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return net.pocrd.api.entity.ApiBookInfo.internal_static_net_pocrd_api_entity_Api_BookInfo_fieldAccessorTable;
    }
    
    private int bitField0_;
    // optional int32 crid = 1;
    public static final int CRID_FIELD_NUMBER = 1;
    private int crid_;
    public boolean hasCrid() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public int getCrid() {
      return crid_;
    }
    
    // optional int32 bookid = 2;
    public static final int BOOKID_FIELD_NUMBER = 2;
    private int bookid_;
    public boolean hasBookid() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public int getBookid() {
      return bookid_;
    }
    
    // optional string bookName = 3;
    public static final int BOOKNAME_FIELD_NUMBER = 3;
    private java.lang.Object bookName_;
    public boolean hasBookName() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public String getBookName() {
      java.lang.Object ref = bookName_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          bookName_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getBookNameBytes() {
      java.lang.Object ref = bookName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        bookName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string author = 4;
    public static final int AUTHOR_FIELD_NUMBER = 4;
    private java.lang.Object author_;
    public boolean hasAuthor() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public String getAuthor() {
      java.lang.Object ref = author_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          author_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getAuthorBytes() {
      java.lang.Object ref = author_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        author_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional int32 authorid = 5;
    public static final int AUTHORID_FIELD_NUMBER = 5;
    private int authorid_;
    public boolean hasAuthorid() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    public int getAuthorid() {
      return authorid_;
    }
    
    // optional string url = 6;
    public static final int URL_FIELD_NUMBER = 6;
    private java.lang.Object url_;
    public boolean hasUrl() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    public String getUrl() {
      java.lang.Object ref = url_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          url_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getUrlBytes() {
      java.lang.Object ref = url_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        url_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    private void initFields() {
      crid_ = 0;
      bookid_ = 0;
      bookName_ = "";
      author_ = "";
      authorid_ = 0;
      url_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, crid_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, bookid_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getBookNameBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getAuthorBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeInt32(5, authorid_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeBytes(6, getUrlBytes());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, crid_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, bookid_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getBookNameBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getAuthorBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, authorid_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(6, getUrlBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static net.pocrd.api.entity.ApiBookInfo.Api_BookInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static net.pocrd.api.entity.ApiBookInfo.Api_BookInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static net.pocrd.api.entity.ApiBookInfo.Api_BookInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static net.pocrd.api.entity.ApiBookInfo.Api_BookInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static net.pocrd.api.entity.ApiBookInfo.Api_BookInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static net.pocrd.api.entity.ApiBookInfo.Api_BookInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static net.pocrd.api.entity.ApiBookInfo.Api_BookInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static net.pocrd.api.entity.ApiBookInfo.Api_BookInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static net.pocrd.api.entity.ApiBookInfo.Api_BookInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static net.pocrd.api.entity.ApiBookInfo.Api_BookInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(net.pocrd.api.entity.ApiBookInfo.Api_BookInfo prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements net.pocrd.api.entity.ApiBookInfo.Api_BookInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return net.pocrd.api.entity.ApiBookInfo.internal_static_net_pocrd_api_entity_Api_BookInfo_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return net.pocrd.api.entity.ApiBookInfo.internal_static_net_pocrd_api_entity_Api_BookInfo_fieldAccessorTable;
      }
      
      // Construct using net.pocrd.api.entity.ApiBookInfo.Api_BookInfo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        crid_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        bookid_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        bookName_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        author_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        authorid_ = 0;
        bitField0_ = (bitField0_ & ~0x00000010);
        url_ = "";
        bitField0_ = (bitField0_ & ~0x00000020);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return net.pocrd.api.entity.ApiBookInfo.Api_BookInfo.getDescriptor();
      }
      
      public net.pocrd.api.entity.ApiBookInfo.Api_BookInfo getDefaultInstanceForType() {
        return net.pocrd.api.entity.ApiBookInfo.Api_BookInfo.getDefaultInstance();
      }
      
      public net.pocrd.api.entity.ApiBookInfo.Api_BookInfo build() {
        net.pocrd.api.entity.ApiBookInfo.Api_BookInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private net.pocrd.api.entity.ApiBookInfo.Api_BookInfo buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        net.pocrd.api.entity.ApiBookInfo.Api_BookInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public net.pocrd.api.entity.ApiBookInfo.Api_BookInfo buildPartial() {
        net.pocrd.api.entity.ApiBookInfo.Api_BookInfo result = new net.pocrd.api.entity.ApiBookInfo.Api_BookInfo(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.crid_ = crid_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.bookid_ = bookid_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.bookName_ = bookName_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.author_ = author_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.authorid_ = authorid_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.url_ = url_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof net.pocrd.api.entity.ApiBookInfo.Api_BookInfo) {
          return mergeFrom((net.pocrd.api.entity.ApiBookInfo.Api_BookInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(net.pocrd.api.entity.ApiBookInfo.Api_BookInfo other) {
        if (other == net.pocrd.api.entity.ApiBookInfo.Api_BookInfo.getDefaultInstance()) return this;
        if (other.hasCrid()) {
          setCrid(other.getCrid());
        }
        if (other.hasBookid()) {
          setBookid(other.getBookid());
        }
        if (other.hasBookName()) {
          setBookName(other.getBookName());
        }
        if (other.hasAuthor()) {
          setAuthor(other.getAuthor());
        }
        if (other.hasAuthorid()) {
          setAuthorid(other.getAuthorid());
        }
        if (other.hasUrl()) {
          setUrl(other.getUrl());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              crid_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              bookid_ = input.readInt32();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              bookName_ = input.readBytes();
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              author_ = input.readBytes();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              authorid_ = input.readInt32();
              break;
            }
            case 50: {
              bitField0_ |= 0x00000020;
              url_ = input.readBytes();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // optional int32 crid = 1;
      private int crid_ ;
      public boolean hasCrid() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public int getCrid() {
        return crid_;
      }
      public Builder setCrid(int value) {
        bitField0_ |= 0x00000001;
        crid_ = value;
        onChanged();
        return this;
      }
      public Builder clearCrid() {
        bitField0_ = (bitField0_ & ~0x00000001);
        crid_ = 0;
        onChanged();
        return this;
      }
      
      // optional int32 bookid = 2;
      private int bookid_ ;
      public boolean hasBookid() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public int getBookid() {
        return bookid_;
      }
      public Builder setBookid(int value) {
        bitField0_ |= 0x00000002;
        bookid_ = value;
        onChanged();
        return this;
      }
      public Builder clearBookid() {
        bitField0_ = (bitField0_ & ~0x00000002);
        bookid_ = 0;
        onChanged();
        return this;
      }
      
      // optional string bookName = 3;
      private java.lang.Object bookName_ = "";
      public boolean hasBookName() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public String getBookName() {
        java.lang.Object ref = bookName_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          bookName_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setBookName(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        bookName_ = value;
        onChanged();
        return this;
      }
      public Builder clearBookName() {
        bitField0_ = (bitField0_ & ~0x00000004);
        bookName_ = getDefaultInstance().getBookName();
        onChanged();
        return this;
      }
      void setBookName(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000004;
        bookName_ = value;
        onChanged();
      }
      
      // optional string author = 4;
      private java.lang.Object author_ = "";
      public boolean hasAuthor() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public String getAuthor() {
        java.lang.Object ref = author_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          author_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setAuthor(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        author_ = value;
        onChanged();
        return this;
      }
      public Builder clearAuthor() {
        bitField0_ = (bitField0_ & ~0x00000008);
        author_ = getDefaultInstance().getAuthor();
        onChanged();
        return this;
      }
      void setAuthor(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000008;
        author_ = value;
        onChanged();
      }
      
      // optional int32 authorid = 5;
      private int authorid_ ;
      public boolean hasAuthorid() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      public int getAuthorid() {
        return authorid_;
      }
      public Builder setAuthorid(int value) {
        bitField0_ |= 0x00000010;
        authorid_ = value;
        onChanged();
        return this;
      }
      public Builder clearAuthorid() {
        bitField0_ = (bitField0_ & ~0x00000010);
        authorid_ = 0;
        onChanged();
        return this;
      }
      
      // optional string url = 6;
      private java.lang.Object url_ = "";
      public boolean hasUrl() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      public String getUrl() {
        java.lang.Object ref = url_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          url_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setUrl(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        url_ = value;
        onChanged();
        return this;
      }
      public Builder clearUrl() {
        bitField0_ = (bitField0_ & ~0x00000020);
        url_ = getDefaultInstance().getUrl();
        onChanged();
        return this;
      }
      void setUrl(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000020;
        url_ = value;
        onChanged();
      }
      
      // @@protoc_insertion_point(builder_scope:net.pocrd.api.entity.Api_BookInfo)
    }
    
    static {
      defaultInstance = new Api_BookInfo(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:net.pocrd.api.entity.Api_BookInfo)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_net_pocrd_api_entity_Api_BookInfo_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_net_pocrd_api_entity_Api_BookInfo_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\'net/pocrd/api/entity/Api_BookInfo.prot" +
      "o\022\024net.pocrd.api.entity\"m\n\014Api_BookInfo\022" +
      "\014\n\004crid\030\001 \001(\005\022\016\n\006bookid\030\002 \001(\005\022\020\n\010bookNam" +
      "e\030\003 \001(\t\022\016\n\006author\030\004 \001(\t\022\020\n\010authorid\030\005 \001(" +
      "\005\022\013\n\003url\030\006 \001(\t"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_net_pocrd_api_entity_Api_BookInfo_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_net_pocrd_api_entity_Api_BookInfo_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_net_pocrd_api_entity_Api_BookInfo_descriptor,
              new java.lang.String[] { "Crid", "Bookid", "BookName", "Author", "Authorid", "Url", },
              net.pocrd.api.entity.ApiBookInfo.Api_BookInfo.class,
              net.pocrd.api.entity.ApiBookInfo.Api_BookInfo.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
