// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: net/pocrd/api/resp/Api_List_ProductInfo.proto

package net.pocrd.api.resp;

public final class ApiListProductInfo {
  private ApiListProductInfo() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface Api_List_ProductInfoOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // repeated .net.pocrd.api.resp.Api_ProductInfo productInfo = 1;
    /**
     * <code>repeated .net.pocrd.api.resp.Api_ProductInfo productInfo = 1;</code>
     */
    java.util.List<net.pocrd.api.resp.ApiProductInfo.Api_ProductInfo> 
        getProductInfoList();
    /**
     * <code>repeated .net.pocrd.api.resp.Api_ProductInfo productInfo = 1;</code>
     */
    net.pocrd.api.resp.ApiProductInfo.Api_ProductInfo getProductInfo(int index);
    /**
     * <code>repeated .net.pocrd.api.resp.Api_ProductInfo productInfo = 1;</code>
     */
    int getProductInfoCount();
    /**
     * <code>repeated .net.pocrd.api.resp.Api_ProductInfo productInfo = 1;</code>
     */
    java.util.List<? extends net.pocrd.api.resp.ApiProductInfo.Api_ProductInfoOrBuilder> 
        getProductInfoOrBuilderList();
    /**
     * <code>repeated .net.pocrd.api.resp.Api_ProductInfo productInfo = 1;</code>
     */
    net.pocrd.api.resp.ApiProductInfo.Api_ProductInfoOrBuilder getProductInfoOrBuilder(
        int index);

    // optional int32 totalcount = 2;
    /**
     * <code>optional int32 totalcount = 2;</code>
     */
    boolean hasTotalcount();
    /**
     * <code>optional int32 totalcount = 2;</code>
     */
    int getTotalcount();
  }
  /**
   * Protobuf type {@code net.pocrd.api.resp.Api_List_ProductInfo}
   */
  public static final class Api_List_ProductInfo extends
      com.google.protobuf.GeneratedMessage
      implements Api_List_ProductInfoOrBuilder {
    // Use Api_List_ProductInfo.newBuilder() to construct.
    private Api_List_ProductInfo(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Api_List_ProductInfo(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Api_List_ProductInfo defaultInstance;
    public static Api_List_ProductInfo getDefaultInstance() {
      return defaultInstance;
    }

    public Api_List_ProductInfo getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Api_List_ProductInfo(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                productInfo_ = new java.util.ArrayList<net.pocrd.api.resp.ApiProductInfo.Api_ProductInfo>();
                mutable_bitField0_ |= 0x00000001;
              }
              productInfo_.add(input.readMessage(net.pocrd.api.resp.ApiProductInfo.Api_ProductInfo.PARSER, extensionRegistry));
              break;
            }
            case 16: {
              bitField0_ |= 0x00000001;
              totalcount_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          productInfo_ = java.util.Collections.unmodifiableList(productInfo_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return net.pocrd.api.resp.ApiListProductInfo.internal_static_net_pocrd_api_resp_Api_List_ProductInfo_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return net.pocrd.api.resp.ApiListProductInfo.internal_static_net_pocrd_api_resp_Api_List_ProductInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              net.pocrd.api.resp.ApiListProductInfo.Api_List_ProductInfo.class, net.pocrd.api.resp.ApiListProductInfo.Api_List_ProductInfo.Builder.class);
    }

    public static com.google.protobuf.Parser<Api_List_ProductInfo> PARSER =
        new com.google.protobuf.AbstractParser<Api_List_ProductInfo>() {
      public Api_List_ProductInfo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Api_List_ProductInfo(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Api_List_ProductInfo> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // repeated .net.pocrd.api.resp.Api_ProductInfo productInfo = 1;
    public static final int PRODUCTINFO_FIELD_NUMBER = 1;
    private java.util.List<net.pocrd.api.resp.ApiProductInfo.Api_ProductInfo> productInfo_;
    /**
     * <code>repeated .net.pocrd.api.resp.Api_ProductInfo productInfo = 1;</code>
     */
    public java.util.List<net.pocrd.api.resp.ApiProductInfo.Api_ProductInfo> getProductInfoList() {
      return productInfo_;
    }
    /**
     * <code>repeated .net.pocrd.api.resp.Api_ProductInfo productInfo = 1;</code>
     */
    public java.util.List<? extends net.pocrd.api.resp.ApiProductInfo.Api_ProductInfoOrBuilder> 
        getProductInfoOrBuilderList() {
      return productInfo_;
    }
    /**
     * <code>repeated .net.pocrd.api.resp.Api_ProductInfo productInfo = 1;</code>
     */
    public int getProductInfoCount() {
      return productInfo_.size();
    }
    /**
     * <code>repeated .net.pocrd.api.resp.Api_ProductInfo productInfo = 1;</code>
     */
    public net.pocrd.api.resp.ApiProductInfo.Api_ProductInfo getProductInfo(int index) {
      return productInfo_.get(index);
    }
    /**
     * <code>repeated .net.pocrd.api.resp.Api_ProductInfo productInfo = 1;</code>
     */
    public net.pocrd.api.resp.ApiProductInfo.Api_ProductInfoOrBuilder getProductInfoOrBuilder(
        int index) {
      return productInfo_.get(index);
    }

    // optional int32 totalcount = 2;
    public static final int TOTALCOUNT_FIELD_NUMBER = 2;
    private int totalcount_;
    /**
     * <code>optional int32 totalcount = 2;</code>
     */
    public boolean hasTotalcount() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional int32 totalcount = 2;</code>
     */
    public int getTotalcount() {
      return totalcount_;
    }

    private void initFields() {
      productInfo_ = java.util.Collections.emptyList();
      totalcount_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < productInfo_.size(); i++) {
        output.writeMessage(1, productInfo_.get(i));
      }
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(2, totalcount_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < productInfo_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, productInfo_.get(i));
      }
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, totalcount_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static net.pocrd.api.resp.ApiListProductInfo.Api_List_ProductInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static net.pocrd.api.resp.ApiListProductInfo.Api_List_ProductInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static net.pocrd.api.resp.ApiListProductInfo.Api_List_ProductInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static net.pocrd.api.resp.ApiListProductInfo.Api_List_ProductInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static net.pocrd.api.resp.ApiListProductInfo.Api_List_ProductInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static net.pocrd.api.resp.ApiListProductInfo.Api_List_ProductInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static net.pocrd.api.resp.ApiListProductInfo.Api_List_ProductInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static net.pocrd.api.resp.ApiListProductInfo.Api_List_ProductInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static net.pocrd.api.resp.ApiListProductInfo.Api_List_ProductInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static net.pocrd.api.resp.ApiListProductInfo.Api_List_ProductInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(net.pocrd.api.resp.ApiListProductInfo.Api_List_ProductInfo prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code net.pocrd.api.resp.Api_List_ProductInfo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements net.pocrd.api.resp.ApiListProductInfo.Api_List_ProductInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return net.pocrd.api.resp.ApiListProductInfo.internal_static_net_pocrd_api_resp_Api_List_ProductInfo_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return net.pocrd.api.resp.ApiListProductInfo.internal_static_net_pocrd_api_resp_Api_List_ProductInfo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                net.pocrd.api.resp.ApiListProductInfo.Api_List_ProductInfo.class, net.pocrd.api.resp.ApiListProductInfo.Api_List_ProductInfo.Builder.class);
      }

      // Construct using net.pocrd.api.resp.ApiListProductInfo.Api_List_ProductInfo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getProductInfoFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (productInfoBuilder_ == null) {
          productInfo_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          productInfoBuilder_.clear();
        }
        totalcount_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return net.pocrd.api.resp.ApiListProductInfo.internal_static_net_pocrd_api_resp_Api_List_ProductInfo_descriptor;
      }

      public net.pocrd.api.resp.ApiListProductInfo.Api_List_ProductInfo getDefaultInstanceForType() {
        return net.pocrd.api.resp.ApiListProductInfo.Api_List_ProductInfo.getDefaultInstance();
      }

      public net.pocrd.api.resp.ApiListProductInfo.Api_List_ProductInfo build() {
        net.pocrd.api.resp.ApiListProductInfo.Api_List_ProductInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public net.pocrd.api.resp.ApiListProductInfo.Api_List_ProductInfo buildPartial() {
        net.pocrd.api.resp.ApiListProductInfo.Api_List_ProductInfo result = new net.pocrd.api.resp.ApiListProductInfo.Api_List_ProductInfo(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (productInfoBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            productInfo_ = java.util.Collections.unmodifiableList(productInfo_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.productInfo_ = productInfo_;
        } else {
          result.productInfo_ = productInfoBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000001;
        }
        result.totalcount_ = totalcount_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof net.pocrd.api.resp.ApiListProductInfo.Api_List_ProductInfo) {
          return mergeFrom((net.pocrd.api.resp.ApiListProductInfo.Api_List_ProductInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(net.pocrd.api.resp.ApiListProductInfo.Api_List_ProductInfo other) {
        if (other == net.pocrd.api.resp.ApiListProductInfo.Api_List_ProductInfo.getDefaultInstance()) return this;
        if (productInfoBuilder_ == null) {
          if (!other.productInfo_.isEmpty()) {
            if (productInfo_.isEmpty()) {
              productInfo_ = other.productInfo_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureProductInfoIsMutable();
              productInfo_.addAll(other.productInfo_);
            }
            onChanged();
          }
        } else {
          if (!other.productInfo_.isEmpty()) {
            if (productInfoBuilder_.isEmpty()) {
              productInfoBuilder_.dispose();
              productInfoBuilder_ = null;
              productInfo_ = other.productInfo_;
              bitField0_ = (bitField0_ & ~0x00000001);
              productInfoBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getProductInfoFieldBuilder() : null;
            } else {
              productInfoBuilder_.addAllMessages(other.productInfo_);
            }
          }
        }
        if (other.hasTotalcount()) {
          setTotalcount(other.getTotalcount());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        net.pocrd.api.resp.ApiListProductInfo.Api_List_ProductInfo parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (net.pocrd.api.resp.ApiListProductInfo.Api_List_ProductInfo) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // repeated .net.pocrd.api.resp.Api_ProductInfo productInfo = 1;
      private java.util.List<net.pocrd.api.resp.ApiProductInfo.Api_ProductInfo> productInfo_ =
        java.util.Collections.emptyList();
      private void ensureProductInfoIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          productInfo_ = new java.util.ArrayList<net.pocrd.api.resp.ApiProductInfo.Api_ProductInfo>(productInfo_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          net.pocrd.api.resp.ApiProductInfo.Api_ProductInfo, net.pocrd.api.resp.ApiProductInfo.Api_ProductInfo.Builder, net.pocrd.api.resp.ApiProductInfo.Api_ProductInfoOrBuilder> productInfoBuilder_;

      /**
       * <code>repeated .net.pocrd.api.resp.Api_ProductInfo productInfo = 1;</code>
       */
      public java.util.List<net.pocrd.api.resp.ApiProductInfo.Api_ProductInfo> getProductInfoList() {
        if (productInfoBuilder_ == null) {
          return java.util.Collections.unmodifiableList(productInfo_);
        } else {
          return productInfoBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .net.pocrd.api.resp.Api_ProductInfo productInfo = 1;</code>
       */
      public int getProductInfoCount() {
        if (productInfoBuilder_ == null) {
          return productInfo_.size();
        } else {
          return productInfoBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .net.pocrd.api.resp.Api_ProductInfo productInfo = 1;</code>
       */
      public net.pocrd.api.resp.ApiProductInfo.Api_ProductInfo getProductInfo(int index) {
        if (productInfoBuilder_ == null) {
          return productInfo_.get(index);
        } else {
          return productInfoBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .net.pocrd.api.resp.Api_ProductInfo productInfo = 1;</code>
       */
      public Builder setProductInfo(
          int index, net.pocrd.api.resp.ApiProductInfo.Api_ProductInfo value) {
        if (productInfoBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureProductInfoIsMutable();
          productInfo_.set(index, value);
          onChanged();
        } else {
          productInfoBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .net.pocrd.api.resp.Api_ProductInfo productInfo = 1;</code>
       */
      public Builder setProductInfo(
          int index, net.pocrd.api.resp.ApiProductInfo.Api_ProductInfo.Builder builderForValue) {
        if (productInfoBuilder_ == null) {
          ensureProductInfoIsMutable();
          productInfo_.set(index, builderForValue.build());
          onChanged();
        } else {
          productInfoBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .net.pocrd.api.resp.Api_ProductInfo productInfo = 1;</code>
       */
      public Builder addProductInfo(net.pocrd.api.resp.ApiProductInfo.Api_ProductInfo value) {
        if (productInfoBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureProductInfoIsMutable();
          productInfo_.add(value);
          onChanged();
        } else {
          productInfoBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .net.pocrd.api.resp.Api_ProductInfo productInfo = 1;</code>
       */
      public Builder addProductInfo(
          int index, net.pocrd.api.resp.ApiProductInfo.Api_ProductInfo value) {
        if (productInfoBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureProductInfoIsMutable();
          productInfo_.add(index, value);
          onChanged();
        } else {
          productInfoBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .net.pocrd.api.resp.Api_ProductInfo productInfo = 1;</code>
       */
      public Builder addProductInfo(
          net.pocrd.api.resp.ApiProductInfo.Api_ProductInfo.Builder builderForValue) {
        if (productInfoBuilder_ == null) {
          ensureProductInfoIsMutable();
          productInfo_.add(builderForValue.build());
          onChanged();
        } else {
          productInfoBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .net.pocrd.api.resp.Api_ProductInfo productInfo = 1;</code>
       */
      public Builder addProductInfo(
          int index, net.pocrd.api.resp.ApiProductInfo.Api_ProductInfo.Builder builderForValue) {
        if (productInfoBuilder_ == null) {
          ensureProductInfoIsMutable();
          productInfo_.add(index, builderForValue.build());
          onChanged();
        } else {
          productInfoBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .net.pocrd.api.resp.Api_ProductInfo productInfo = 1;</code>
       */
      public Builder addAllProductInfo(
          java.lang.Iterable<? extends net.pocrd.api.resp.ApiProductInfo.Api_ProductInfo> values) {
        if (productInfoBuilder_ == null) {
          ensureProductInfoIsMutable();
          super.addAll(values, productInfo_);
          onChanged();
        } else {
          productInfoBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .net.pocrd.api.resp.Api_ProductInfo productInfo = 1;</code>
       */
      public Builder clearProductInfo() {
        if (productInfoBuilder_ == null) {
          productInfo_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          productInfoBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .net.pocrd.api.resp.Api_ProductInfo productInfo = 1;</code>
       */
      public Builder removeProductInfo(int index) {
        if (productInfoBuilder_ == null) {
          ensureProductInfoIsMutable();
          productInfo_.remove(index);
          onChanged();
        } else {
          productInfoBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .net.pocrd.api.resp.Api_ProductInfo productInfo = 1;</code>
       */
      public net.pocrd.api.resp.ApiProductInfo.Api_ProductInfo.Builder getProductInfoBuilder(
          int index) {
        return getProductInfoFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .net.pocrd.api.resp.Api_ProductInfo productInfo = 1;</code>
       */
      public net.pocrd.api.resp.ApiProductInfo.Api_ProductInfoOrBuilder getProductInfoOrBuilder(
          int index) {
        if (productInfoBuilder_ == null) {
          return productInfo_.get(index);  } else {
          return productInfoBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .net.pocrd.api.resp.Api_ProductInfo productInfo = 1;</code>
       */
      public java.util.List<? extends net.pocrd.api.resp.ApiProductInfo.Api_ProductInfoOrBuilder> 
           getProductInfoOrBuilderList() {
        if (productInfoBuilder_ != null) {
          return productInfoBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(productInfo_);
        }
      }
      /**
       * <code>repeated .net.pocrd.api.resp.Api_ProductInfo productInfo = 1;</code>
       */
      public net.pocrd.api.resp.ApiProductInfo.Api_ProductInfo.Builder addProductInfoBuilder() {
        return getProductInfoFieldBuilder().addBuilder(
            net.pocrd.api.resp.ApiProductInfo.Api_ProductInfo.getDefaultInstance());
      }
      /**
       * <code>repeated .net.pocrd.api.resp.Api_ProductInfo productInfo = 1;</code>
       */
      public net.pocrd.api.resp.ApiProductInfo.Api_ProductInfo.Builder addProductInfoBuilder(
          int index) {
        return getProductInfoFieldBuilder().addBuilder(
            index, net.pocrd.api.resp.ApiProductInfo.Api_ProductInfo.getDefaultInstance());
      }
      /**
       * <code>repeated .net.pocrd.api.resp.Api_ProductInfo productInfo = 1;</code>
       */
      public java.util.List<net.pocrd.api.resp.ApiProductInfo.Api_ProductInfo.Builder> 
           getProductInfoBuilderList() {
        return getProductInfoFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          net.pocrd.api.resp.ApiProductInfo.Api_ProductInfo, net.pocrd.api.resp.ApiProductInfo.Api_ProductInfo.Builder, net.pocrd.api.resp.ApiProductInfo.Api_ProductInfoOrBuilder> 
          getProductInfoFieldBuilder() {
        if (productInfoBuilder_ == null) {
          productInfoBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              net.pocrd.api.resp.ApiProductInfo.Api_ProductInfo, net.pocrd.api.resp.ApiProductInfo.Api_ProductInfo.Builder, net.pocrd.api.resp.ApiProductInfo.Api_ProductInfoOrBuilder>(
                  productInfo_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          productInfo_ = null;
        }
        return productInfoBuilder_;
      }

      // optional int32 totalcount = 2;
      private int totalcount_ ;
      /**
       * <code>optional int32 totalcount = 2;</code>
       */
      public boolean hasTotalcount() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional int32 totalcount = 2;</code>
       */
      public int getTotalcount() {
        return totalcount_;
      }
      /**
       * <code>optional int32 totalcount = 2;</code>
       */
      public Builder setTotalcount(int value) {
        bitField0_ |= 0x00000002;
        totalcount_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 totalcount = 2;</code>
       */
      public Builder clearTotalcount() {
        bitField0_ = (bitField0_ & ~0x00000002);
        totalcount_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:net.pocrd.api.resp.Api_List_ProductInfo)
    }

    static {
      defaultInstance = new Api_List_ProductInfo(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:net.pocrd.api.resp.Api_List_ProductInfo)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_net_pocrd_api_resp_Api_List_ProductInfo_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_net_pocrd_api_resp_Api_List_ProductInfo_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n-net/pocrd/api/resp/Api_List_ProductInf" +
      "o.proto\022\022net.pocrd.api.resp\032(net/pocrd/a" +
      "pi/resp/Api_ProductInfo.proto\"d\n\024Api_Lis" +
      "t_ProductInfo\0228\n\013productInfo\030\001 \003(\0132#.net" +
      ".pocrd.api.resp.Api_ProductInfo\022\022\n\ntotal" +
      "count\030\002 \001(\005"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_net_pocrd_api_resp_Api_List_ProductInfo_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_net_pocrd_api_resp_Api_List_ProductInfo_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_net_pocrd_api_resp_Api_List_ProductInfo_descriptor,
              new java.lang.String[] { "ProductInfo", "Totalcount", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          net.pocrd.api.resp.ApiProductInfo.getDescriptor(),
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
