// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: net/pocrd/api/resp/Api_LoginResp.proto

package net.pocrd.api.resp;

public final class ApiLoginResp {
  private ApiLoginResp() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface Api_LoginRespOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional string token = 1;
    /**
     * <code>optional string token = 1;</code>
     *
     * <pre>
     * 登录凭据
     * </pre>
     */
    boolean hasToken();
    /**
     * <code>optional string token = 1;</code>
     *
     * <pre>
     * 登录凭据
     * </pre>
     */
    java.lang.String getToken();
    /**
     * <code>optional string token = 1;</code>
     *
     * <pre>
     * 登录凭据
     * </pre>
     */
    com.google.protobuf.ByteString
        getTokenBytes();

    // optional int64 expire = 2;
    /**
     * <code>optional int64 expire = 2;</code>
     *
     * <pre>
     * 过期时间
     * </pre>
     */
    boolean hasExpire();
    /**
     * <code>optional int64 expire = 2;</code>
     *
     * <pre>
     * 过期时间
     * </pre>
     */
    long getExpire();

    // optional int64 uid = 3;
    /**
     * <code>optional int64 uid = 3;</code>
     *
     * <pre>
     * 用户id
     * </pre>
     */
    boolean hasUid();
    /**
     * <code>optional int64 uid = 3;</code>
     *
     * <pre>
     * 用户id
     * </pre>
     */
    long getUid();

    // optional string oaUserid = 4;
    /**
     * <code>optional string oaUserid = 4;</code>
     *
     * <pre>
     * 第三方用户id
     * </pre>
     */
    boolean hasOaUserid();
    /**
     * <code>optional string oaUserid = 4;</code>
     *
     * <pre>
     * 第三方用户id
     * </pre>
     */
    java.lang.String getOaUserid();
    /**
     * <code>optional string oaUserid = 4;</code>
     *
     * <pre>
     * 第三方用户id
     * </pre>
     */
    com.google.protobuf.ByteString
        getOaUseridBytes();

    // optional string oaType = 5;
    /**
     * <code>optional string oaType = 5;</code>
     *
     * <pre>
     * 第三方接入类型
     * </pre>
     */
    boolean hasOaType();
    /**
     * <code>optional string oaType = 5;</code>
     *
     * <pre>
     * 第三方接入类型
     * </pre>
     */
    java.lang.String getOaType();
    /**
     * <code>optional string oaType = 5;</code>
     *
     * <pre>
     * 第三方接入类型
     * </pre>
     */
    com.google.protobuf.ByteString
        getOaTypeBytes();

    // optional string oaToken = 6;
    /**
     * <code>optional string oaToken = 6;</code>
     *
     * <pre>
     * 第三方token
     * </pre>
     */
    boolean hasOaToken();
    /**
     * <code>optional string oaToken = 6;</code>
     *
     * <pre>
     * 第三方token
     * </pre>
     */
    java.lang.String getOaToken();
    /**
     * <code>optional string oaToken = 6;</code>
     *
     * <pre>
     * 第三方token
     * </pre>
     */
    com.google.protobuf.ByteString
        getOaTokenBytes();

    // optional string nickname = 7;
    /**
     * <code>optional string nickname = 7;</code>
     *
     * <pre>
     * 昵称
     * </pre>
     */
    boolean hasNickname();
    /**
     * <code>optional string nickname = 7;</code>
     *
     * <pre>
     * 昵称
     * </pre>
     */
    java.lang.String getNickname();
    /**
     * <code>optional string nickname = 7;</code>
     *
     * <pre>
     * 昵称
     * </pre>
     */
    com.google.protobuf.ByteString
        getNicknameBytes();
  }
  /**
   * Protobuf type {@code net.pocrd.api.resp.Api_LoginResp}
   */
  public static final class Api_LoginResp extends
      com.google.protobuf.GeneratedMessage
      implements Api_LoginRespOrBuilder {
    // Use Api_LoginResp.newBuilder() to construct.
    private Api_LoginResp(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Api_LoginResp(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Api_LoginResp defaultInstance;
    public static Api_LoginResp getDefaultInstance() {
      return defaultInstance;
    }

    public Api_LoginResp getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Api_LoginResp(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              token_ = input.readBytes();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              expire_ = input.readInt64();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              uid_ = input.readInt64();
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              oaUserid_ = input.readBytes();
              break;
            }
            case 42: {
              bitField0_ |= 0x00000010;
              oaType_ = input.readBytes();
              break;
            }
            case 50: {
              bitField0_ |= 0x00000020;
              oaToken_ = input.readBytes();
              break;
            }
            case 58: {
              bitField0_ |= 0x00000040;
              nickname_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return net.pocrd.api.resp.ApiLoginResp.internal_static_net_pocrd_api_resp_Api_LoginResp_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return net.pocrd.api.resp.ApiLoginResp.internal_static_net_pocrd_api_resp_Api_LoginResp_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              net.pocrd.api.resp.ApiLoginResp.Api_LoginResp.class, net.pocrd.api.resp.ApiLoginResp.Api_LoginResp.Builder.class);
    }

    public static com.google.protobuf.Parser<Api_LoginResp> PARSER =
        new com.google.protobuf.AbstractParser<Api_LoginResp>() {
      public Api_LoginResp parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Api_LoginResp(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Api_LoginResp> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional string token = 1;
    public static final int TOKEN_FIELD_NUMBER = 1;
    private java.lang.Object token_;
    /**
     * <code>optional string token = 1;</code>
     *
     * <pre>
     * 登录凭据
     * </pre>
     */
    public boolean hasToken() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional string token = 1;</code>
     *
     * <pre>
     * 登录凭据
     * </pre>
     */
    public java.lang.String getToken() {
      java.lang.Object ref = token_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          token_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string token = 1;</code>
     *
     * <pre>
     * 登录凭据
     * </pre>
     */
    public com.google.protobuf.ByteString
        getTokenBytes() {
      java.lang.Object ref = token_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        token_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional int64 expire = 2;
    public static final int EXPIRE_FIELD_NUMBER = 2;
    private long expire_;
    /**
     * <code>optional int64 expire = 2;</code>
     *
     * <pre>
     * 过期时间
     * </pre>
     */
    public boolean hasExpire() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional int64 expire = 2;</code>
     *
     * <pre>
     * 过期时间
     * </pre>
     */
    public long getExpire() {
      return expire_;
    }

    // optional int64 uid = 3;
    public static final int UID_FIELD_NUMBER = 3;
    private long uid_;
    /**
     * <code>optional int64 uid = 3;</code>
     *
     * <pre>
     * 用户id
     * </pre>
     */
    public boolean hasUid() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional int64 uid = 3;</code>
     *
     * <pre>
     * 用户id
     * </pre>
     */
    public long getUid() {
      return uid_;
    }

    // optional string oaUserid = 4;
    public static final int OAUSERID_FIELD_NUMBER = 4;
    private java.lang.Object oaUserid_;
    /**
     * <code>optional string oaUserid = 4;</code>
     *
     * <pre>
     * 第三方用户id
     * </pre>
     */
    public boolean hasOaUserid() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional string oaUserid = 4;</code>
     *
     * <pre>
     * 第三方用户id
     * </pre>
     */
    public java.lang.String getOaUserid() {
      java.lang.Object ref = oaUserid_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          oaUserid_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string oaUserid = 4;</code>
     *
     * <pre>
     * 第三方用户id
     * </pre>
     */
    public com.google.protobuf.ByteString
        getOaUseridBytes() {
      java.lang.Object ref = oaUserid_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        oaUserid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string oaType = 5;
    public static final int OATYPE_FIELD_NUMBER = 5;
    private java.lang.Object oaType_;
    /**
     * <code>optional string oaType = 5;</code>
     *
     * <pre>
     * 第三方接入类型
     * </pre>
     */
    public boolean hasOaType() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional string oaType = 5;</code>
     *
     * <pre>
     * 第三方接入类型
     * </pre>
     */
    public java.lang.String getOaType() {
      java.lang.Object ref = oaType_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          oaType_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string oaType = 5;</code>
     *
     * <pre>
     * 第三方接入类型
     * </pre>
     */
    public com.google.protobuf.ByteString
        getOaTypeBytes() {
      java.lang.Object ref = oaType_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        oaType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string oaToken = 6;
    public static final int OATOKEN_FIELD_NUMBER = 6;
    private java.lang.Object oaToken_;
    /**
     * <code>optional string oaToken = 6;</code>
     *
     * <pre>
     * 第三方token
     * </pre>
     */
    public boolean hasOaToken() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional string oaToken = 6;</code>
     *
     * <pre>
     * 第三方token
     * </pre>
     */
    public java.lang.String getOaToken() {
      java.lang.Object ref = oaToken_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          oaToken_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string oaToken = 6;</code>
     *
     * <pre>
     * 第三方token
     * </pre>
     */
    public com.google.protobuf.ByteString
        getOaTokenBytes() {
      java.lang.Object ref = oaToken_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        oaToken_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string nickname = 7;
    public static final int NICKNAME_FIELD_NUMBER = 7;
    private java.lang.Object nickname_;
    /**
     * <code>optional string nickname = 7;</code>
     *
     * <pre>
     * 昵称
     * </pre>
     */
    public boolean hasNickname() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>optional string nickname = 7;</code>
     *
     * <pre>
     * 昵称
     * </pre>
     */
    public java.lang.String getNickname() {
      java.lang.Object ref = nickname_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          nickname_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string nickname = 7;</code>
     *
     * <pre>
     * 昵称
     * </pre>
     */
    public com.google.protobuf.ByteString
        getNicknameBytes() {
      java.lang.Object ref = nickname_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        nickname_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      token_ = "";
      expire_ = 0L;
      uid_ = 0L;
      oaUserid_ = "";
      oaType_ = "";
      oaToken_ = "";
      nickname_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getTokenBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt64(2, expire_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt64(3, uid_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getOaUseridBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBytes(5, getOaTypeBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeBytes(6, getOaTokenBytes());
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeBytes(7, getNicknameBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getTokenBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, expire_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, uid_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getOaUseridBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, getOaTypeBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(6, getOaTokenBytes());
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(7, getNicknameBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static net.pocrd.api.resp.ApiLoginResp.Api_LoginResp parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static net.pocrd.api.resp.ApiLoginResp.Api_LoginResp parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static net.pocrd.api.resp.ApiLoginResp.Api_LoginResp parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static net.pocrd.api.resp.ApiLoginResp.Api_LoginResp parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static net.pocrd.api.resp.ApiLoginResp.Api_LoginResp parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static net.pocrd.api.resp.ApiLoginResp.Api_LoginResp parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static net.pocrd.api.resp.ApiLoginResp.Api_LoginResp parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static net.pocrd.api.resp.ApiLoginResp.Api_LoginResp parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static net.pocrd.api.resp.ApiLoginResp.Api_LoginResp parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static net.pocrd.api.resp.ApiLoginResp.Api_LoginResp parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(net.pocrd.api.resp.ApiLoginResp.Api_LoginResp prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code net.pocrd.api.resp.Api_LoginResp}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements net.pocrd.api.resp.ApiLoginResp.Api_LoginRespOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return net.pocrd.api.resp.ApiLoginResp.internal_static_net_pocrd_api_resp_Api_LoginResp_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return net.pocrd.api.resp.ApiLoginResp.internal_static_net_pocrd_api_resp_Api_LoginResp_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                net.pocrd.api.resp.ApiLoginResp.Api_LoginResp.class, net.pocrd.api.resp.ApiLoginResp.Api_LoginResp.Builder.class);
      }

      // Construct using net.pocrd.api.resp.ApiLoginResp.Api_LoginResp.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        token_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        expire_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000002);
        uid_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000004);
        oaUserid_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        oaType_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        oaToken_ = "";
        bitField0_ = (bitField0_ & ~0x00000020);
        nickname_ = "";
        bitField0_ = (bitField0_ & ~0x00000040);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return net.pocrd.api.resp.ApiLoginResp.internal_static_net_pocrd_api_resp_Api_LoginResp_descriptor;
      }

      public net.pocrd.api.resp.ApiLoginResp.Api_LoginResp getDefaultInstanceForType() {
        return net.pocrd.api.resp.ApiLoginResp.Api_LoginResp.getDefaultInstance();
      }

      public net.pocrd.api.resp.ApiLoginResp.Api_LoginResp build() {
        net.pocrd.api.resp.ApiLoginResp.Api_LoginResp result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public net.pocrd.api.resp.ApiLoginResp.Api_LoginResp buildPartial() {
        net.pocrd.api.resp.ApiLoginResp.Api_LoginResp result = new net.pocrd.api.resp.ApiLoginResp.Api_LoginResp(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.token_ = token_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.expire_ = expire_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.uid_ = uid_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.oaUserid_ = oaUserid_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.oaType_ = oaType_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.oaToken_ = oaToken_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.nickname_ = nickname_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof net.pocrd.api.resp.ApiLoginResp.Api_LoginResp) {
          return mergeFrom((net.pocrd.api.resp.ApiLoginResp.Api_LoginResp)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(net.pocrd.api.resp.ApiLoginResp.Api_LoginResp other) {
        if (other == net.pocrd.api.resp.ApiLoginResp.Api_LoginResp.getDefaultInstance()) return this;
        if (other.hasToken()) {
          bitField0_ |= 0x00000001;
          token_ = other.token_;
          onChanged();
        }
        if (other.hasExpire()) {
          setExpire(other.getExpire());
        }
        if (other.hasUid()) {
          setUid(other.getUid());
        }
        if (other.hasOaUserid()) {
          bitField0_ |= 0x00000008;
          oaUserid_ = other.oaUserid_;
          onChanged();
        }
        if (other.hasOaType()) {
          bitField0_ |= 0x00000010;
          oaType_ = other.oaType_;
          onChanged();
        }
        if (other.hasOaToken()) {
          bitField0_ |= 0x00000020;
          oaToken_ = other.oaToken_;
          onChanged();
        }
        if (other.hasNickname()) {
          bitField0_ |= 0x00000040;
          nickname_ = other.nickname_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        net.pocrd.api.resp.ApiLoginResp.Api_LoginResp parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (net.pocrd.api.resp.ApiLoginResp.Api_LoginResp) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional string token = 1;
      private java.lang.Object token_ = "";
      /**
       * <code>optional string token = 1;</code>
       *
       * <pre>
       * 登录凭据
       * </pre>
       */
      public boolean hasToken() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional string token = 1;</code>
       *
       * <pre>
       * 登录凭据
       * </pre>
       */
      public java.lang.String getToken() {
        java.lang.Object ref = token_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          token_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string token = 1;</code>
       *
       * <pre>
       * 登录凭据
       * </pre>
       */
      public com.google.protobuf.ByteString
          getTokenBytes() {
        java.lang.Object ref = token_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          token_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string token = 1;</code>
       *
       * <pre>
       * 登录凭据
       * </pre>
       */
      public Builder setToken(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        token_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string token = 1;</code>
       *
       * <pre>
       * 登录凭据
       * </pre>
       */
      public Builder clearToken() {
        bitField0_ = (bitField0_ & ~0x00000001);
        token_ = getDefaultInstance().getToken();
        onChanged();
        return this;
      }
      /**
       * <code>optional string token = 1;</code>
       *
       * <pre>
       * 登录凭据
       * </pre>
       */
      public Builder setTokenBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        token_ = value;
        onChanged();
        return this;
      }

      // optional int64 expire = 2;
      private long expire_ ;
      /**
       * <code>optional int64 expire = 2;</code>
       *
       * <pre>
       * 过期时间
       * </pre>
       */
      public boolean hasExpire() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional int64 expire = 2;</code>
       *
       * <pre>
       * 过期时间
       * </pre>
       */
      public long getExpire() {
        return expire_;
      }
      /**
       * <code>optional int64 expire = 2;</code>
       *
       * <pre>
       * 过期时间
       * </pre>
       */
      public Builder setExpire(long value) {
        bitField0_ |= 0x00000002;
        expire_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 expire = 2;</code>
       *
       * <pre>
       * 过期时间
       * </pre>
       */
      public Builder clearExpire() {
        bitField0_ = (bitField0_ & ~0x00000002);
        expire_ = 0L;
        onChanged();
        return this;
      }

      // optional int64 uid = 3;
      private long uid_ ;
      /**
       * <code>optional int64 uid = 3;</code>
       *
       * <pre>
       * 用户id
       * </pre>
       */
      public boolean hasUid() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional int64 uid = 3;</code>
       *
       * <pre>
       * 用户id
       * </pre>
       */
      public long getUid() {
        return uid_;
      }
      /**
       * <code>optional int64 uid = 3;</code>
       *
       * <pre>
       * 用户id
       * </pre>
       */
      public Builder setUid(long value) {
        bitField0_ |= 0x00000004;
        uid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 uid = 3;</code>
       *
       * <pre>
       * 用户id
       * </pre>
       */
      public Builder clearUid() {
        bitField0_ = (bitField0_ & ~0x00000004);
        uid_ = 0L;
        onChanged();
        return this;
      }

      // optional string oaUserid = 4;
      private java.lang.Object oaUserid_ = "";
      /**
       * <code>optional string oaUserid = 4;</code>
       *
       * <pre>
       * 第三方用户id
       * </pre>
       */
      public boolean hasOaUserid() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional string oaUserid = 4;</code>
       *
       * <pre>
       * 第三方用户id
       * </pre>
       */
      public java.lang.String getOaUserid() {
        java.lang.Object ref = oaUserid_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          oaUserid_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string oaUserid = 4;</code>
       *
       * <pre>
       * 第三方用户id
       * </pre>
       */
      public com.google.protobuf.ByteString
          getOaUseridBytes() {
        java.lang.Object ref = oaUserid_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          oaUserid_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string oaUserid = 4;</code>
       *
       * <pre>
       * 第三方用户id
       * </pre>
       */
      public Builder setOaUserid(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        oaUserid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string oaUserid = 4;</code>
       *
       * <pre>
       * 第三方用户id
       * </pre>
       */
      public Builder clearOaUserid() {
        bitField0_ = (bitField0_ & ~0x00000008);
        oaUserid_ = getDefaultInstance().getOaUserid();
        onChanged();
        return this;
      }
      /**
       * <code>optional string oaUserid = 4;</code>
       *
       * <pre>
       * 第三方用户id
       * </pre>
       */
      public Builder setOaUseridBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        oaUserid_ = value;
        onChanged();
        return this;
      }

      // optional string oaType = 5;
      private java.lang.Object oaType_ = "";
      /**
       * <code>optional string oaType = 5;</code>
       *
       * <pre>
       * 第三方接入类型
       * </pre>
       */
      public boolean hasOaType() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional string oaType = 5;</code>
       *
       * <pre>
       * 第三方接入类型
       * </pre>
       */
      public java.lang.String getOaType() {
        java.lang.Object ref = oaType_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          oaType_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string oaType = 5;</code>
       *
       * <pre>
       * 第三方接入类型
       * </pre>
       */
      public com.google.protobuf.ByteString
          getOaTypeBytes() {
        java.lang.Object ref = oaType_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          oaType_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string oaType = 5;</code>
       *
       * <pre>
       * 第三方接入类型
       * </pre>
       */
      public Builder setOaType(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        oaType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string oaType = 5;</code>
       *
       * <pre>
       * 第三方接入类型
       * </pre>
       */
      public Builder clearOaType() {
        bitField0_ = (bitField0_ & ~0x00000010);
        oaType_ = getDefaultInstance().getOaType();
        onChanged();
        return this;
      }
      /**
       * <code>optional string oaType = 5;</code>
       *
       * <pre>
       * 第三方接入类型
       * </pre>
       */
      public Builder setOaTypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        oaType_ = value;
        onChanged();
        return this;
      }

      // optional string oaToken = 6;
      private java.lang.Object oaToken_ = "";
      /**
       * <code>optional string oaToken = 6;</code>
       *
       * <pre>
       * 第三方token
       * </pre>
       */
      public boolean hasOaToken() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>optional string oaToken = 6;</code>
       *
       * <pre>
       * 第三方token
       * </pre>
       */
      public java.lang.String getOaToken() {
        java.lang.Object ref = oaToken_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          oaToken_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string oaToken = 6;</code>
       *
       * <pre>
       * 第三方token
       * </pre>
       */
      public com.google.protobuf.ByteString
          getOaTokenBytes() {
        java.lang.Object ref = oaToken_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          oaToken_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string oaToken = 6;</code>
       *
       * <pre>
       * 第三方token
       * </pre>
       */
      public Builder setOaToken(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        oaToken_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string oaToken = 6;</code>
       *
       * <pre>
       * 第三方token
       * </pre>
       */
      public Builder clearOaToken() {
        bitField0_ = (bitField0_ & ~0x00000020);
        oaToken_ = getDefaultInstance().getOaToken();
        onChanged();
        return this;
      }
      /**
       * <code>optional string oaToken = 6;</code>
       *
       * <pre>
       * 第三方token
       * </pre>
       */
      public Builder setOaTokenBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        oaToken_ = value;
        onChanged();
        return this;
      }

      // optional string nickname = 7;
      private java.lang.Object nickname_ = "";
      /**
       * <code>optional string nickname = 7;</code>
       *
       * <pre>
       * 昵称
       * </pre>
       */
      public boolean hasNickname() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>optional string nickname = 7;</code>
       *
       * <pre>
       * 昵称
       * </pre>
       */
      public java.lang.String getNickname() {
        java.lang.Object ref = nickname_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          nickname_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string nickname = 7;</code>
       *
       * <pre>
       * 昵称
       * </pre>
       */
      public com.google.protobuf.ByteString
          getNicknameBytes() {
        java.lang.Object ref = nickname_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          nickname_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string nickname = 7;</code>
       *
       * <pre>
       * 昵称
       * </pre>
       */
      public Builder setNickname(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        nickname_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string nickname = 7;</code>
       *
       * <pre>
       * 昵称
       * </pre>
       */
      public Builder clearNickname() {
        bitField0_ = (bitField0_ & ~0x00000040);
        nickname_ = getDefaultInstance().getNickname();
        onChanged();
        return this;
      }
      /**
       * <code>optional string nickname = 7;</code>
       *
       * <pre>
       * 昵称
       * </pre>
       */
      public Builder setNicknameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        nickname_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:net.pocrd.api.resp.Api_LoginResp)
    }

    static {
      defaultInstance = new Api_LoginResp(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:net.pocrd.api.resp.Api_LoginResp)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_net_pocrd_api_resp_Api_LoginResp_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_net_pocrd_api_resp_Api_LoginResp_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n&net/pocrd/api/resp/Api_LoginResp.proto" +
      "\022\022net.pocrd.api.resp\"\200\001\n\rApi_LoginResp\022\r" +
      "\n\005token\030\001 \001(\t\022\016\n\006expire\030\002 \001(\003\022\013\n\003uid\030\003 \001" +
      "(\003\022\020\n\010oaUserid\030\004 \001(\t\022\016\n\006oaType\030\005 \001(\t\022\017\n\007" +
      "oaToken\030\006 \001(\t\022\020\n\010nickname\030\007 \001(\t"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_net_pocrd_api_resp_Api_LoginResp_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_net_pocrd_api_resp_Api_LoginResp_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_net_pocrd_api_resp_Api_LoginResp_descriptor,
              new java.lang.String[] { "Token", "Expire", "Uid", "OaUserid", "OaType", "OaToken", "Nickname", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
