// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: net/pocrd/api/resp/Api_Notification.proto

package net.pocrd.api.resp;

public final class ApiNotification {
  private ApiNotification() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface Api_NotificationOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // optional int32 what = 1;
    boolean hasWhat();
    int getWhat();
    
    // repeated string arg = 2;
    java.util.List<String> getArgList();
    int getArgCount();
    String getArg(int index);
  }
  public static final class Api_Notification extends
      com.google.protobuf.GeneratedMessage
      implements Api_NotificationOrBuilder {
    // Use Api_Notification.newBuilder() to construct.
    private Api_Notification(Builder builder) {
      super(builder);
    }
    private Api_Notification(boolean noInit) {}
    
    private static final Api_Notification defaultInstance;
    public static Api_Notification getDefaultInstance() {
      return defaultInstance;
    }
    
    public Api_Notification getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return net.pocrd.api.resp.ApiNotification.internal_static_net_pocrd_api_resp_Api_Notification_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return net.pocrd.api.resp.ApiNotification.internal_static_net_pocrd_api_resp_Api_Notification_fieldAccessorTable;
    }
    
    private int bitField0_;
    // optional int32 what = 1;
    public static final int WHAT_FIELD_NUMBER = 1;
    private int what_;
    public boolean hasWhat() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public int getWhat() {
      return what_;
    }
    
    // repeated string arg = 2;
    public static final int ARG_FIELD_NUMBER = 2;
    private com.google.protobuf.LazyStringList arg_;
    public java.util.List<String>
        getArgList() {
      return arg_;
    }
    public int getArgCount() {
      return arg_.size();
    }
    public String getArg(int index) {
      return arg_.get(index);
    }
    
    private void initFields() {
      what_ = 0;
      arg_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, what_);
      }
      for (int i = 0; i < arg_.size(); i++) {
        output.writeBytes(2, arg_.getByteString(i));
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, what_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < arg_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(arg_.getByteString(i));
        }
        size += dataSize;
        size += 1 * getArgList().size();
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static net.pocrd.api.resp.ApiNotification.Api_Notification parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static net.pocrd.api.resp.ApiNotification.Api_Notification parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static net.pocrd.api.resp.ApiNotification.Api_Notification parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static net.pocrd.api.resp.ApiNotification.Api_Notification parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static net.pocrd.api.resp.ApiNotification.Api_Notification parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static net.pocrd.api.resp.ApiNotification.Api_Notification parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static net.pocrd.api.resp.ApiNotification.Api_Notification parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static net.pocrd.api.resp.ApiNotification.Api_Notification parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static net.pocrd.api.resp.ApiNotification.Api_Notification parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static net.pocrd.api.resp.ApiNotification.Api_Notification parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(net.pocrd.api.resp.ApiNotification.Api_Notification prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements net.pocrd.api.resp.ApiNotification.Api_NotificationOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return net.pocrd.api.resp.ApiNotification.internal_static_net_pocrd_api_resp_Api_Notification_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return net.pocrd.api.resp.ApiNotification.internal_static_net_pocrd_api_resp_Api_Notification_fieldAccessorTable;
      }
      
      // Construct using net.pocrd.api.resp.ApiNotification.Api_Notification.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        what_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        arg_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return net.pocrd.api.resp.ApiNotification.Api_Notification.getDescriptor();
      }
      
      public net.pocrd.api.resp.ApiNotification.Api_Notification getDefaultInstanceForType() {
        return net.pocrd.api.resp.ApiNotification.Api_Notification.getDefaultInstance();
      }
      
      public net.pocrd.api.resp.ApiNotification.Api_Notification build() {
        net.pocrd.api.resp.ApiNotification.Api_Notification result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private net.pocrd.api.resp.ApiNotification.Api_Notification buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        net.pocrd.api.resp.ApiNotification.Api_Notification result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public net.pocrd.api.resp.ApiNotification.Api_Notification buildPartial() {
        net.pocrd.api.resp.ApiNotification.Api_Notification result = new net.pocrd.api.resp.ApiNotification.Api_Notification(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.what_ = what_;
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          arg_ = new com.google.protobuf.UnmodifiableLazyStringList(
              arg_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.arg_ = arg_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof net.pocrd.api.resp.ApiNotification.Api_Notification) {
          return mergeFrom((net.pocrd.api.resp.ApiNotification.Api_Notification)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(net.pocrd.api.resp.ApiNotification.Api_Notification other) {
        if (other == net.pocrd.api.resp.ApiNotification.Api_Notification.getDefaultInstance()) return this;
        if (other.hasWhat()) {
          setWhat(other.getWhat());
        }
        if (!other.arg_.isEmpty()) {
          if (arg_.isEmpty()) {
            arg_ = other.arg_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureArgIsMutable();
            arg_.addAll(other.arg_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              what_ = input.readInt32();
              break;
            }
            case 18: {
              ensureArgIsMutable();
              arg_.add(input.readBytes());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // optional int32 what = 1;
      private int what_ ;
      public boolean hasWhat() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public int getWhat() {
        return what_;
      }
      public Builder setWhat(int value) {
        bitField0_ |= 0x00000001;
        what_ = value;
        onChanged();
        return this;
      }
      public Builder clearWhat() {
        bitField0_ = (bitField0_ & ~0x00000001);
        what_ = 0;
        onChanged();
        return this;
      }
      
      // repeated string arg = 2;
      private com.google.protobuf.LazyStringList arg_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureArgIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          arg_ = new com.google.protobuf.LazyStringArrayList(arg_);
          bitField0_ |= 0x00000002;
         }
      }
      public java.util.List<String>
          getArgList() {
        return java.util.Collections.unmodifiableList(arg_);
      }
      public int getArgCount() {
        return arg_.size();
      }
      public String getArg(int index) {
        return arg_.get(index);
      }
      public Builder setArg(
          int index, String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureArgIsMutable();
        arg_.set(index, value);
        onChanged();
        return this;
      }
      public Builder addArg(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureArgIsMutable();
        arg_.add(value);
        onChanged();
        return this;
      }
      public Builder addAllArg(
          java.lang.Iterable<String> values) {
        ensureArgIsMutable();
        super.addAll(values, arg_);
        onChanged();
        return this;
      }
      public Builder clearArg() {
        arg_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      void addArg(com.google.protobuf.ByteString value) {
        ensureArgIsMutable();
        arg_.add(value);
        onChanged();
      }
      
      // @@protoc_insertion_point(builder_scope:net.pocrd.api.resp.Api_Notification)
    }
    
    static {
      defaultInstance = new Api_Notification(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:net.pocrd.api.resp.Api_Notification)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_net_pocrd_api_resp_Api_Notification_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_net_pocrd_api_resp_Api_Notification_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n)net/pocrd/api/resp/Api_Notification.pr" +
      "oto\022\022net.pocrd.api.resp\"-\n\020Api_Notificat" +
      "ion\022\014\n\004what\030\001 \001(\005\022\013\n\003arg\030\002 \003(\t"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_net_pocrd_api_resp_Api_Notification_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_net_pocrd_api_resp_Api_Notification_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_net_pocrd_api_resp_Api_Notification_descriptor,
              new java.lang.String[] { "What", "Arg", },
              net.pocrd.api.resp.ApiNotification.Api_Notification.class,
              net.pocrd.api.resp.ApiNotification.Api_Notification.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
