// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: net/pocrd/api/resp/Api_ProductInfo.proto

package net.pocrd.api.resp;

public final class ApiProductInfo {
  private ApiProductInfo() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface Api_ProductInfoOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // optional int32 productId = 1;
    boolean hasProductId();
    int getProductId();
    
    // optional string productName = 2;
    boolean hasProductName();
    String getProductName();
    
    // optional int32 corporationId = 3;
    boolean hasCorporationId();
    int getCorporationId();
    
    // optional string corporationName = 4;
    boolean hasCorporationName();
    String getCorporationName();
    
    // optional int32 ceiling = 5;
    boolean hasCeiling();
    int getCeiling();
    
    // optional int32 cycle = 7;
    boolean hasCycle();
    int getCycle();
    
    // optional double rate = 8;
    boolean hasRate();
    double getRate();
    
    // optional int32 categoryId = 9;
    boolean hasCategoryId();
    int getCategoryId();
    
    // optional string categoryName = 10;
    boolean hasCategoryName();
    String getCategoryName();
    
    // optional string ageRange = 11;
    boolean hasAgeRange();
    String getAgeRange();
    
    // optional int32 floorWorkExp = 12;
    boolean hasFloorWorkExp();
    int getFloorWorkExp();
    
    // optional string industry = 13;
    boolean hasIndustry();
    String getIndustry();
    
    // optional int32 floorSalary = 14;
    boolean hasFloorSalary();
    int getFloorSalary();
    
    // optional string location = 15;
    boolean hasLocation();
    String getLocation();
    
    // optional string mortgage = 16;
    boolean hasMortgage();
    String getMortgage();
    
    // optional string material = 17;
    boolean hasMaterial();
    String getMaterial();
    
    // optional string releaseTime = 18;
    boolean hasReleaseTime();
    String getReleaseTime();
    
    // optional string otherReq = 19;
    boolean hasOtherReq();
    String getOtherReq();
    
    // optional int32 interest = 20;
    boolean hasInterest();
    int getInterest();
    
    // optional int32 monthlyPayamount = 21;
    boolean hasMonthlyPayamount();
    int getMonthlyPayamount();
  }
  public static final class Api_ProductInfo extends
      com.google.protobuf.GeneratedMessage
      implements Api_ProductInfoOrBuilder {
    // Use Api_ProductInfo.newBuilder() to construct.
    private Api_ProductInfo(Builder builder) {
      super(builder);
    }
    private Api_ProductInfo(boolean noInit) {}
    
    private static final Api_ProductInfo defaultInstance;
    public static Api_ProductInfo getDefaultInstance() {
      return defaultInstance;
    }
    
    public Api_ProductInfo getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return net.pocrd.api.resp.ApiProductInfo.internal_static_net_pocrd_api_resp_Api_ProductInfo_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return net.pocrd.api.resp.ApiProductInfo.internal_static_net_pocrd_api_resp_Api_ProductInfo_fieldAccessorTable;
    }
    
    private int bitField0_;
    // optional int32 productId = 1;
    public static final int PRODUCTID_FIELD_NUMBER = 1;
    private int productId_;
    public boolean hasProductId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public int getProductId() {
      return productId_;
    }
    
    // optional string productName = 2;
    public static final int PRODUCTNAME_FIELD_NUMBER = 2;
    private java.lang.Object productName_;
    public boolean hasProductName() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public String getProductName() {
      java.lang.Object ref = productName_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          productName_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getProductNameBytes() {
      java.lang.Object ref = productName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        productName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional int32 corporationId = 3;
    public static final int CORPORATIONID_FIELD_NUMBER = 3;
    private int corporationId_;
    public boolean hasCorporationId() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public int getCorporationId() {
      return corporationId_;
    }
    
    // optional string corporationName = 4;
    public static final int CORPORATIONNAME_FIELD_NUMBER = 4;
    private java.lang.Object corporationName_;
    public boolean hasCorporationName() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public String getCorporationName() {
      java.lang.Object ref = corporationName_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          corporationName_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getCorporationNameBytes() {
      java.lang.Object ref = corporationName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        corporationName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional int32 ceiling = 5;
    public static final int CEILING_FIELD_NUMBER = 5;
    private int ceiling_;
    public boolean hasCeiling() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    public int getCeiling() {
      return ceiling_;
    }
    
    // optional int32 cycle = 7;
    public static final int CYCLE_FIELD_NUMBER = 7;
    private int cycle_;
    public boolean hasCycle() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    public int getCycle() {
      return cycle_;
    }
    
    // optional double rate = 8;
    public static final int RATE_FIELD_NUMBER = 8;
    private double rate_;
    public boolean hasRate() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    public double getRate() {
      return rate_;
    }
    
    // optional int32 categoryId = 9;
    public static final int CATEGORYID_FIELD_NUMBER = 9;
    private int categoryId_;
    public boolean hasCategoryId() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    public int getCategoryId() {
      return categoryId_;
    }
    
    // optional string categoryName = 10;
    public static final int CATEGORYNAME_FIELD_NUMBER = 10;
    private java.lang.Object categoryName_;
    public boolean hasCategoryName() {
      return ((bitField0_ & 0x00000100) == 0x00000100);
    }
    public String getCategoryName() {
      java.lang.Object ref = categoryName_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          categoryName_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getCategoryNameBytes() {
      java.lang.Object ref = categoryName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        categoryName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string ageRange = 11;
    public static final int AGERANGE_FIELD_NUMBER = 11;
    private java.lang.Object ageRange_;
    public boolean hasAgeRange() {
      return ((bitField0_ & 0x00000200) == 0x00000200);
    }
    public String getAgeRange() {
      java.lang.Object ref = ageRange_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          ageRange_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getAgeRangeBytes() {
      java.lang.Object ref = ageRange_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        ageRange_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional int32 floorWorkExp = 12;
    public static final int FLOORWORKEXP_FIELD_NUMBER = 12;
    private int floorWorkExp_;
    public boolean hasFloorWorkExp() {
      return ((bitField0_ & 0x00000400) == 0x00000400);
    }
    public int getFloorWorkExp() {
      return floorWorkExp_;
    }
    
    // optional string industry = 13;
    public static final int INDUSTRY_FIELD_NUMBER = 13;
    private java.lang.Object industry_;
    public boolean hasIndustry() {
      return ((bitField0_ & 0x00000800) == 0x00000800);
    }
    public String getIndustry() {
      java.lang.Object ref = industry_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          industry_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getIndustryBytes() {
      java.lang.Object ref = industry_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        industry_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional int32 floorSalary = 14;
    public static final int FLOORSALARY_FIELD_NUMBER = 14;
    private int floorSalary_;
    public boolean hasFloorSalary() {
      return ((bitField0_ & 0x00001000) == 0x00001000);
    }
    public int getFloorSalary() {
      return floorSalary_;
    }
    
    // optional string location = 15;
    public static final int LOCATION_FIELD_NUMBER = 15;
    private java.lang.Object location_;
    public boolean hasLocation() {
      return ((bitField0_ & 0x00002000) == 0x00002000);
    }
    public String getLocation() {
      java.lang.Object ref = location_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          location_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getLocationBytes() {
      java.lang.Object ref = location_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        location_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string mortgage = 16;
    public static final int MORTGAGE_FIELD_NUMBER = 16;
    private java.lang.Object mortgage_;
    public boolean hasMortgage() {
      return ((bitField0_ & 0x00004000) == 0x00004000);
    }
    public String getMortgage() {
      java.lang.Object ref = mortgage_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          mortgage_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getMortgageBytes() {
      java.lang.Object ref = mortgage_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        mortgage_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string material = 17;
    public static final int MATERIAL_FIELD_NUMBER = 17;
    private java.lang.Object material_;
    public boolean hasMaterial() {
      return ((bitField0_ & 0x00008000) == 0x00008000);
    }
    public String getMaterial() {
      java.lang.Object ref = material_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          material_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getMaterialBytes() {
      java.lang.Object ref = material_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        material_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string releaseTime = 18;
    public static final int RELEASETIME_FIELD_NUMBER = 18;
    private java.lang.Object releaseTime_;
    public boolean hasReleaseTime() {
      return ((bitField0_ & 0x00010000) == 0x00010000);
    }
    public String getReleaseTime() {
      java.lang.Object ref = releaseTime_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          releaseTime_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getReleaseTimeBytes() {
      java.lang.Object ref = releaseTime_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        releaseTime_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string otherReq = 19;
    public static final int OTHERREQ_FIELD_NUMBER = 19;
    private java.lang.Object otherReq_;
    public boolean hasOtherReq() {
      return ((bitField0_ & 0x00020000) == 0x00020000);
    }
    public String getOtherReq() {
      java.lang.Object ref = otherReq_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          otherReq_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getOtherReqBytes() {
      java.lang.Object ref = otherReq_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        otherReq_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional int32 interest = 20;
    public static final int INTEREST_FIELD_NUMBER = 20;
    private int interest_;
    public boolean hasInterest() {
      return ((bitField0_ & 0x00040000) == 0x00040000);
    }
    public int getInterest() {
      return interest_;
    }
    
    // optional int32 monthlyPayamount = 21;
    public static final int MONTHLYPAYAMOUNT_FIELD_NUMBER = 21;
    private int monthlyPayamount_;
    public boolean hasMonthlyPayamount() {
      return ((bitField0_ & 0x00080000) == 0x00080000);
    }
    public int getMonthlyPayamount() {
      return monthlyPayamount_;
    }
    
    private void initFields() {
      productId_ = 0;
      productName_ = "";
      corporationId_ = 0;
      corporationName_ = "";
      ceiling_ = 0;
      cycle_ = 0;
      rate_ = 0D;
      categoryId_ = 0;
      categoryName_ = "";
      ageRange_ = "";
      floorWorkExp_ = 0;
      industry_ = "";
      floorSalary_ = 0;
      location_ = "";
      mortgage_ = "";
      material_ = "";
      releaseTime_ = "";
      otherReq_ = "";
      interest_ = 0;
      monthlyPayamount_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, productId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getProductNameBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, corporationId_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getCorporationNameBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeInt32(5, ceiling_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeInt32(7, cycle_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeDouble(8, rate_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        output.writeInt32(9, categoryId_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        output.writeBytes(10, getCategoryNameBytes());
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        output.writeBytes(11, getAgeRangeBytes());
      }
      if (((bitField0_ & 0x00000400) == 0x00000400)) {
        output.writeInt32(12, floorWorkExp_);
      }
      if (((bitField0_ & 0x00000800) == 0x00000800)) {
        output.writeBytes(13, getIndustryBytes());
      }
      if (((bitField0_ & 0x00001000) == 0x00001000)) {
        output.writeInt32(14, floorSalary_);
      }
      if (((bitField0_ & 0x00002000) == 0x00002000)) {
        output.writeBytes(15, getLocationBytes());
      }
      if (((bitField0_ & 0x00004000) == 0x00004000)) {
        output.writeBytes(16, getMortgageBytes());
      }
      if (((bitField0_ & 0x00008000) == 0x00008000)) {
        output.writeBytes(17, getMaterialBytes());
      }
      if (((bitField0_ & 0x00010000) == 0x00010000)) {
        output.writeBytes(18, getReleaseTimeBytes());
      }
      if (((bitField0_ & 0x00020000) == 0x00020000)) {
        output.writeBytes(19, getOtherReqBytes());
      }
      if (((bitField0_ & 0x00040000) == 0x00040000)) {
        output.writeInt32(20, interest_);
      }
      if (((bitField0_ & 0x00080000) == 0x00080000)) {
        output.writeInt32(21, monthlyPayamount_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, productId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getProductNameBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, corporationId_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getCorporationNameBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, ceiling_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(7, cycle_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(8, rate_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(9, categoryId_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(10, getCategoryNameBytes());
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(11, getAgeRangeBytes());
      }
      if (((bitField0_ & 0x00000400) == 0x00000400)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(12, floorWorkExp_);
      }
      if (((bitField0_ & 0x00000800) == 0x00000800)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(13, getIndustryBytes());
      }
      if (((bitField0_ & 0x00001000) == 0x00001000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(14, floorSalary_);
      }
      if (((bitField0_ & 0x00002000) == 0x00002000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(15, getLocationBytes());
      }
      if (((bitField0_ & 0x00004000) == 0x00004000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(16, getMortgageBytes());
      }
      if (((bitField0_ & 0x00008000) == 0x00008000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(17, getMaterialBytes());
      }
      if (((bitField0_ & 0x00010000) == 0x00010000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(18, getReleaseTimeBytes());
      }
      if (((bitField0_ & 0x00020000) == 0x00020000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(19, getOtherReqBytes());
      }
      if (((bitField0_ & 0x00040000) == 0x00040000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(20, interest_);
      }
      if (((bitField0_ & 0x00080000) == 0x00080000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(21, monthlyPayamount_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static net.pocrd.api.resp.ApiProductInfo.Api_ProductInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static net.pocrd.api.resp.ApiProductInfo.Api_ProductInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static net.pocrd.api.resp.ApiProductInfo.Api_ProductInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static net.pocrd.api.resp.ApiProductInfo.Api_ProductInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static net.pocrd.api.resp.ApiProductInfo.Api_ProductInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static net.pocrd.api.resp.ApiProductInfo.Api_ProductInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static net.pocrd.api.resp.ApiProductInfo.Api_ProductInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static net.pocrd.api.resp.ApiProductInfo.Api_ProductInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static net.pocrd.api.resp.ApiProductInfo.Api_ProductInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static net.pocrd.api.resp.ApiProductInfo.Api_ProductInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(net.pocrd.api.resp.ApiProductInfo.Api_ProductInfo prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements net.pocrd.api.resp.ApiProductInfo.Api_ProductInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return net.pocrd.api.resp.ApiProductInfo.internal_static_net_pocrd_api_resp_Api_ProductInfo_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return net.pocrd.api.resp.ApiProductInfo.internal_static_net_pocrd_api_resp_Api_ProductInfo_fieldAccessorTable;
      }
      
      // Construct using net.pocrd.api.resp.ApiProductInfo.Api_ProductInfo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        productId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        productName_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        corporationId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        corporationName_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        ceiling_ = 0;
        bitField0_ = (bitField0_ & ~0x00000010);
        cycle_ = 0;
        bitField0_ = (bitField0_ & ~0x00000020);
        rate_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000040);
        categoryId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000080);
        categoryName_ = "";
        bitField0_ = (bitField0_ & ~0x00000100);
        ageRange_ = "";
        bitField0_ = (bitField0_ & ~0x00000200);
        floorWorkExp_ = 0;
        bitField0_ = (bitField0_ & ~0x00000400);
        industry_ = "";
        bitField0_ = (bitField0_ & ~0x00000800);
        floorSalary_ = 0;
        bitField0_ = (bitField0_ & ~0x00001000);
        location_ = "";
        bitField0_ = (bitField0_ & ~0x00002000);
        mortgage_ = "";
        bitField0_ = (bitField0_ & ~0x00004000);
        material_ = "";
        bitField0_ = (bitField0_ & ~0x00008000);
        releaseTime_ = "";
        bitField0_ = (bitField0_ & ~0x00010000);
        otherReq_ = "";
        bitField0_ = (bitField0_ & ~0x00020000);
        interest_ = 0;
        bitField0_ = (bitField0_ & ~0x00040000);
        monthlyPayamount_ = 0;
        bitField0_ = (bitField0_ & ~0x00080000);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return net.pocrd.api.resp.ApiProductInfo.Api_ProductInfo.getDescriptor();
      }
      
      public net.pocrd.api.resp.ApiProductInfo.Api_ProductInfo getDefaultInstanceForType() {
        return net.pocrd.api.resp.ApiProductInfo.Api_ProductInfo.getDefaultInstance();
      }
      
      public net.pocrd.api.resp.ApiProductInfo.Api_ProductInfo build() {
        net.pocrd.api.resp.ApiProductInfo.Api_ProductInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private net.pocrd.api.resp.ApiProductInfo.Api_ProductInfo buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        net.pocrd.api.resp.ApiProductInfo.Api_ProductInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public net.pocrd.api.resp.ApiProductInfo.Api_ProductInfo buildPartial() {
        net.pocrd.api.resp.ApiProductInfo.Api_ProductInfo result = new net.pocrd.api.resp.ApiProductInfo.Api_ProductInfo(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.productId_ = productId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.productName_ = productName_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.corporationId_ = corporationId_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.corporationName_ = corporationName_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.ceiling_ = ceiling_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.cycle_ = cycle_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.rate_ = rate_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000080;
        }
        result.categoryId_ = categoryId_;
        if (((from_bitField0_ & 0x00000100) == 0x00000100)) {
          to_bitField0_ |= 0x00000100;
        }
        result.categoryName_ = categoryName_;
        if (((from_bitField0_ & 0x00000200) == 0x00000200)) {
          to_bitField0_ |= 0x00000200;
        }
        result.ageRange_ = ageRange_;
        if (((from_bitField0_ & 0x00000400) == 0x00000400)) {
          to_bitField0_ |= 0x00000400;
        }
        result.floorWorkExp_ = floorWorkExp_;
        if (((from_bitField0_ & 0x00000800) == 0x00000800)) {
          to_bitField0_ |= 0x00000800;
        }
        result.industry_ = industry_;
        if (((from_bitField0_ & 0x00001000) == 0x00001000)) {
          to_bitField0_ |= 0x00001000;
        }
        result.floorSalary_ = floorSalary_;
        if (((from_bitField0_ & 0x00002000) == 0x00002000)) {
          to_bitField0_ |= 0x00002000;
        }
        result.location_ = location_;
        if (((from_bitField0_ & 0x00004000) == 0x00004000)) {
          to_bitField0_ |= 0x00004000;
        }
        result.mortgage_ = mortgage_;
        if (((from_bitField0_ & 0x00008000) == 0x00008000)) {
          to_bitField0_ |= 0x00008000;
        }
        result.material_ = material_;
        if (((from_bitField0_ & 0x00010000) == 0x00010000)) {
          to_bitField0_ |= 0x00010000;
        }
        result.releaseTime_ = releaseTime_;
        if (((from_bitField0_ & 0x00020000) == 0x00020000)) {
          to_bitField0_ |= 0x00020000;
        }
        result.otherReq_ = otherReq_;
        if (((from_bitField0_ & 0x00040000) == 0x00040000)) {
          to_bitField0_ |= 0x00040000;
        }
        result.interest_ = interest_;
        if (((from_bitField0_ & 0x00080000) == 0x00080000)) {
          to_bitField0_ |= 0x00080000;
        }
        result.monthlyPayamount_ = monthlyPayamount_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof net.pocrd.api.resp.ApiProductInfo.Api_ProductInfo) {
          return mergeFrom((net.pocrd.api.resp.ApiProductInfo.Api_ProductInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(net.pocrd.api.resp.ApiProductInfo.Api_ProductInfo other) {
        if (other == net.pocrd.api.resp.ApiProductInfo.Api_ProductInfo.getDefaultInstance()) return this;
        if (other.hasProductId()) {
          setProductId(other.getProductId());
        }
        if (other.hasProductName()) {
          setProductName(other.getProductName());
        }
        if (other.hasCorporationId()) {
          setCorporationId(other.getCorporationId());
        }
        if (other.hasCorporationName()) {
          setCorporationName(other.getCorporationName());
        }
        if (other.hasCeiling()) {
          setCeiling(other.getCeiling());
        }
        if (other.hasCycle()) {
          setCycle(other.getCycle());
        }
        if (other.hasRate()) {
          setRate(other.getRate());
        }
        if (other.hasCategoryId()) {
          setCategoryId(other.getCategoryId());
        }
        if (other.hasCategoryName()) {
          setCategoryName(other.getCategoryName());
        }
        if (other.hasAgeRange()) {
          setAgeRange(other.getAgeRange());
        }
        if (other.hasFloorWorkExp()) {
          setFloorWorkExp(other.getFloorWorkExp());
        }
        if (other.hasIndustry()) {
          setIndustry(other.getIndustry());
        }
        if (other.hasFloorSalary()) {
          setFloorSalary(other.getFloorSalary());
        }
        if (other.hasLocation()) {
          setLocation(other.getLocation());
        }
        if (other.hasMortgage()) {
          setMortgage(other.getMortgage());
        }
        if (other.hasMaterial()) {
          setMaterial(other.getMaterial());
        }
        if (other.hasReleaseTime()) {
          setReleaseTime(other.getReleaseTime());
        }
        if (other.hasOtherReq()) {
          setOtherReq(other.getOtherReq());
        }
        if (other.hasInterest()) {
          setInterest(other.getInterest());
        }
        if (other.hasMonthlyPayamount()) {
          setMonthlyPayamount(other.getMonthlyPayamount());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              productId_ = input.readInt32();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              productName_ = input.readBytes();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              corporationId_ = input.readInt32();
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              corporationName_ = input.readBytes();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              ceiling_ = input.readInt32();
              break;
            }
            case 56: {
              bitField0_ |= 0x00000020;
              cycle_ = input.readInt32();
              break;
            }
            case 65: {
              bitField0_ |= 0x00000040;
              rate_ = input.readDouble();
              break;
            }
            case 72: {
              bitField0_ |= 0x00000080;
              categoryId_ = input.readInt32();
              break;
            }
            case 82: {
              bitField0_ |= 0x00000100;
              categoryName_ = input.readBytes();
              break;
            }
            case 90: {
              bitField0_ |= 0x00000200;
              ageRange_ = input.readBytes();
              break;
            }
            case 96: {
              bitField0_ |= 0x00000400;
              floorWorkExp_ = input.readInt32();
              break;
            }
            case 106: {
              bitField0_ |= 0x00000800;
              industry_ = input.readBytes();
              break;
            }
            case 112: {
              bitField0_ |= 0x00001000;
              floorSalary_ = input.readInt32();
              break;
            }
            case 122: {
              bitField0_ |= 0x00002000;
              location_ = input.readBytes();
              break;
            }
            case 130: {
              bitField0_ |= 0x00004000;
              mortgage_ = input.readBytes();
              break;
            }
            case 138: {
              bitField0_ |= 0x00008000;
              material_ = input.readBytes();
              break;
            }
            case 146: {
              bitField0_ |= 0x00010000;
              releaseTime_ = input.readBytes();
              break;
            }
            case 154: {
              bitField0_ |= 0x00020000;
              otherReq_ = input.readBytes();
              break;
            }
            case 160: {
              bitField0_ |= 0x00040000;
              interest_ = input.readInt32();
              break;
            }
            case 168: {
              bitField0_ |= 0x00080000;
              monthlyPayamount_ = input.readInt32();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // optional int32 productId = 1;
      private int productId_ ;
      public boolean hasProductId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public int getProductId() {
        return productId_;
      }
      public Builder setProductId(int value) {
        bitField0_ |= 0x00000001;
        productId_ = value;
        onChanged();
        return this;
      }
      public Builder clearProductId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        productId_ = 0;
        onChanged();
        return this;
      }
      
      // optional string productName = 2;
      private java.lang.Object productName_ = "";
      public boolean hasProductName() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public String getProductName() {
        java.lang.Object ref = productName_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          productName_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setProductName(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        productName_ = value;
        onChanged();
        return this;
      }
      public Builder clearProductName() {
        bitField0_ = (bitField0_ & ~0x00000002);
        productName_ = getDefaultInstance().getProductName();
        onChanged();
        return this;
      }
      void setProductName(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000002;
        productName_ = value;
        onChanged();
      }
      
      // optional int32 corporationId = 3;
      private int corporationId_ ;
      public boolean hasCorporationId() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public int getCorporationId() {
        return corporationId_;
      }
      public Builder setCorporationId(int value) {
        bitField0_ |= 0x00000004;
        corporationId_ = value;
        onChanged();
        return this;
      }
      public Builder clearCorporationId() {
        bitField0_ = (bitField0_ & ~0x00000004);
        corporationId_ = 0;
        onChanged();
        return this;
      }
      
      // optional string corporationName = 4;
      private java.lang.Object corporationName_ = "";
      public boolean hasCorporationName() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public String getCorporationName() {
        java.lang.Object ref = corporationName_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          corporationName_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setCorporationName(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        corporationName_ = value;
        onChanged();
        return this;
      }
      public Builder clearCorporationName() {
        bitField0_ = (bitField0_ & ~0x00000008);
        corporationName_ = getDefaultInstance().getCorporationName();
        onChanged();
        return this;
      }
      void setCorporationName(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000008;
        corporationName_ = value;
        onChanged();
      }
      
      // optional int32 ceiling = 5;
      private int ceiling_ ;
      public boolean hasCeiling() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      public int getCeiling() {
        return ceiling_;
      }
      public Builder setCeiling(int value) {
        bitField0_ |= 0x00000010;
        ceiling_ = value;
        onChanged();
        return this;
      }
      public Builder clearCeiling() {
        bitField0_ = (bitField0_ & ~0x00000010);
        ceiling_ = 0;
        onChanged();
        return this;
      }
      
      // optional int32 cycle = 7;
      private int cycle_ ;
      public boolean hasCycle() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      public int getCycle() {
        return cycle_;
      }
      public Builder setCycle(int value) {
        bitField0_ |= 0x00000020;
        cycle_ = value;
        onChanged();
        return this;
      }
      public Builder clearCycle() {
        bitField0_ = (bitField0_ & ~0x00000020);
        cycle_ = 0;
        onChanged();
        return this;
      }
      
      // optional double rate = 8;
      private double rate_ ;
      public boolean hasRate() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      public double getRate() {
        return rate_;
      }
      public Builder setRate(double value) {
        bitField0_ |= 0x00000040;
        rate_ = value;
        onChanged();
        return this;
      }
      public Builder clearRate() {
        bitField0_ = (bitField0_ & ~0x00000040);
        rate_ = 0D;
        onChanged();
        return this;
      }
      
      // optional int32 categoryId = 9;
      private int categoryId_ ;
      public boolean hasCategoryId() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      public int getCategoryId() {
        return categoryId_;
      }
      public Builder setCategoryId(int value) {
        bitField0_ |= 0x00000080;
        categoryId_ = value;
        onChanged();
        return this;
      }
      public Builder clearCategoryId() {
        bitField0_ = (bitField0_ & ~0x00000080);
        categoryId_ = 0;
        onChanged();
        return this;
      }
      
      // optional string categoryName = 10;
      private java.lang.Object categoryName_ = "";
      public boolean hasCategoryName() {
        return ((bitField0_ & 0x00000100) == 0x00000100);
      }
      public String getCategoryName() {
        java.lang.Object ref = categoryName_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          categoryName_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setCategoryName(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000100;
        categoryName_ = value;
        onChanged();
        return this;
      }
      public Builder clearCategoryName() {
        bitField0_ = (bitField0_ & ~0x00000100);
        categoryName_ = getDefaultInstance().getCategoryName();
        onChanged();
        return this;
      }
      void setCategoryName(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000100;
        categoryName_ = value;
        onChanged();
      }
      
      // optional string ageRange = 11;
      private java.lang.Object ageRange_ = "";
      public boolean hasAgeRange() {
        return ((bitField0_ & 0x00000200) == 0x00000200);
      }
      public String getAgeRange() {
        java.lang.Object ref = ageRange_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          ageRange_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setAgeRange(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000200;
        ageRange_ = value;
        onChanged();
        return this;
      }
      public Builder clearAgeRange() {
        bitField0_ = (bitField0_ & ~0x00000200);
        ageRange_ = getDefaultInstance().getAgeRange();
        onChanged();
        return this;
      }
      void setAgeRange(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000200;
        ageRange_ = value;
        onChanged();
      }
      
      // optional int32 floorWorkExp = 12;
      private int floorWorkExp_ ;
      public boolean hasFloorWorkExp() {
        return ((bitField0_ & 0x00000400) == 0x00000400);
      }
      public int getFloorWorkExp() {
        return floorWorkExp_;
      }
      public Builder setFloorWorkExp(int value) {
        bitField0_ |= 0x00000400;
        floorWorkExp_ = value;
        onChanged();
        return this;
      }
      public Builder clearFloorWorkExp() {
        bitField0_ = (bitField0_ & ~0x00000400);
        floorWorkExp_ = 0;
        onChanged();
        return this;
      }
      
      // optional string industry = 13;
      private java.lang.Object industry_ = "";
      public boolean hasIndustry() {
        return ((bitField0_ & 0x00000800) == 0x00000800);
      }
      public String getIndustry() {
        java.lang.Object ref = industry_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          industry_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setIndustry(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000800;
        industry_ = value;
        onChanged();
        return this;
      }
      public Builder clearIndustry() {
        bitField0_ = (bitField0_ & ~0x00000800);
        industry_ = getDefaultInstance().getIndustry();
        onChanged();
        return this;
      }
      void setIndustry(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000800;
        industry_ = value;
        onChanged();
      }
      
      // optional int32 floorSalary = 14;
      private int floorSalary_ ;
      public boolean hasFloorSalary() {
        return ((bitField0_ & 0x00001000) == 0x00001000);
      }
      public int getFloorSalary() {
        return floorSalary_;
      }
      public Builder setFloorSalary(int value) {
        bitField0_ |= 0x00001000;
        floorSalary_ = value;
        onChanged();
        return this;
      }
      public Builder clearFloorSalary() {
        bitField0_ = (bitField0_ & ~0x00001000);
        floorSalary_ = 0;
        onChanged();
        return this;
      }
      
      // optional string location = 15;
      private java.lang.Object location_ = "";
      public boolean hasLocation() {
        return ((bitField0_ & 0x00002000) == 0x00002000);
      }
      public String getLocation() {
        java.lang.Object ref = location_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          location_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setLocation(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00002000;
        location_ = value;
        onChanged();
        return this;
      }
      public Builder clearLocation() {
        bitField0_ = (bitField0_ & ~0x00002000);
        location_ = getDefaultInstance().getLocation();
        onChanged();
        return this;
      }
      void setLocation(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00002000;
        location_ = value;
        onChanged();
      }
      
      // optional string mortgage = 16;
      private java.lang.Object mortgage_ = "";
      public boolean hasMortgage() {
        return ((bitField0_ & 0x00004000) == 0x00004000);
      }
      public String getMortgage() {
        java.lang.Object ref = mortgage_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          mortgage_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setMortgage(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00004000;
        mortgage_ = value;
        onChanged();
        return this;
      }
      public Builder clearMortgage() {
        bitField0_ = (bitField0_ & ~0x00004000);
        mortgage_ = getDefaultInstance().getMortgage();
        onChanged();
        return this;
      }
      void setMortgage(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00004000;
        mortgage_ = value;
        onChanged();
      }
      
      // optional string material = 17;
      private java.lang.Object material_ = "";
      public boolean hasMaterial() {
        return ((bitField0_ & 0x00008000) == 0x00008000);
      }
      public String getMaterial() {
        java.lang.Object ref = material_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          material_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setMaterial(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00008000;
        material_ = value;
        onChanged();
        return this;
      }
      public Builder clearMaterial() {
        bitField0_ = (bitField0_ & ~0x00008000);
        material_ = getDefaultInstance().getMaterial();
        onChanged();
        return this;
      }
      void setMaterial(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00008000;
        material_ = value;
        onChanged();
      }
      
      // optional string releaseTime = 18;
      private java.lang.Object releaseTime_ = "";
      public boolean hasReleaseTime() {
        return ((bitField0_ & 0x00010000) == 0x00010000);
      }
      public String getReleaseTime() {
        java.lang.Object ref = releaseTime_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          releaseTime_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setReleaseTime(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00010000;
        releaseTime_ = value;
        onChanged();
        return this;
      }
      public Builder clearReleaseTime() {
        bitField0_ = (bitField0_ & ~0x00010000);
        releaseTime_ = getDefaultInstance().getReleaseTime();
        onChanged();
        return this;
      }
      void setReleaseTime(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00010000;
        releaseTime_ = value;
        onChanged();
      }
      
      // optional string otherReq = 19;
      private java.lang.Object otherReq_ = "";
      public boolean hasOtherReq() {
        return ((bitField0_ & 0x00020000) == 0x00020000);
      }
      public String getOtherReq() {
        java.lang.Object ref = otherReq_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          otherReq_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setOtherReq(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00020000;
        otherReq_ = value;
        onChanged();
        return this;
      }
      public Builder clearOtherReq() {
        bitField0_ = (bitField0_ & ~0x00020000);
        otherReq_ = getDefaultInstance().getOtherReq();
        onChanged();
        return this;
      }
      void setOtherReq(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00020000;
        otherReq_ = value;
        onChanged();
      }
      
      // optional int32 interest = 20;
      private int interest_ ;
      public boolean hasInterest() {
        return ((bitField0_ & 0x00040000) == 0x00040000);
      }
      public int getInterest() {
        return interest_;
      }
      public Builder setInterest(int value) {
        bitField0_ |= 0x00040000;
        interest_ = value;
        onChanged();
        return this;
      }
      public Builder clearInterest() {
        bitField0_ = (bitField0_ & ~0x00040000);
        interest_ = 0;
        onChanged();
        return this;
      }
      
      // optional int32 monthlyPayamount = 21;
      private int monthlyPayamount_ ;
      public boolean hasMonthlyPayamount() {
        return ((bitField0_ & 0x00080000) == 0x00080000);
      }
      public int getMonthlyPayamount() {
        return monthlyPayamount_;
      }
      public Builder setMonthlyPayamount(int value) {
        bitField0_ |= 0x00080000;
        monthlyPayamount_ = value;
        onChanged();
        return this;
      }
      public Builder clearMonthlyPayamount() {
        bitField0_ = (bitField0_ & ~0x00080000);
        monthlyPayamount_ = 0;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:net.pocrd.api.resp.Api_ProductInfo)
    }
    
    static {
      defaultInstance = new Api_ProductInfo(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:net.pocrd.api.resp.Api_ProductInfo)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_net_pocrd_api_resp_Api_ProductInfo_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_net_pocrd_api_resp_Api_ProductInfo_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n(net/pocrd/api/resp/Api_ProductInfo.pro" +
      "to\022\022net.pocrd.api.resp\"\231\003\n\017Api_ProductIn" +
      "fo\022\021\n\tproductId\030\001 \001(\005\022\023\n\013productName\030\002 \001" +
      "(\t\022\025\n\rcorporationId\030\003 \001(\005\022\027\n\017corporation" +
      "Name\030\004 \001(\t\022\017\n\007ceiling\030\005 \001(\005\022\r\n\005cycle\030\007 \001" +
      "(\005\022\014\n\004rate\030\010 \001(\001\022\022\n\ncategoryId\030\t \001(\005\022\024\n\014" +
      "categoryName\030\n \001(\t\022\020\n\010ageRange\030\013 \001(\t\022\024\n\014" +
      "floorWorkExp\030\014 \001(\005\022\020\n\010industry\030\r \001(\t\022\023\n\013" +
      "floorSalary\030\016 \001(\005\022\020\n\010location\030\017 \001(\t\022\020\n\010m" +
      "ortgage\030\020 \001(\t\022\020\n\010material\030\021 \001(\t\022\023\n\013relea",
      "seTime\030\022 \001(\t\022\020\n\010otherReq\030\023 \001(\t\022\020\n\010intere" +
      "st\030\024 \001(\005\022\030\n\020monthlyPayamount\030\025 \001(\005"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_net_pocrd_api_resp_Api_ProductInfo_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_net_pocrd_api_resp_Api_ProductInfo_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_net_pocrd_api_resp_Api_ProductInfo_descriptor,
              new java.lang.String[] { "ProductId", "ProductName", "CorporationId", "CorporationName", "Ceiling", "Cycle", "Rate", "CategoryId", "CategoryName", "AgeRange", "FloorWorkExp", "Industry", "FloorSalary", "Location", "Mortgage", "Material", "ReleaseTime", "OtherReq", "Interest", "MonthlyPayamount", },
              net.pocrd.api.resp.ApiProductInfo.Api_ProductInfo.class,
              net.pocrd.api.resp.ApiProductInfo.Api_ProductInfo.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
